# This is a basic workflow to help you get started with Actions

name: iOS Builder

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-12
    environment: development

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Setup Go environment
        uses: actions/setup-go@v3.3.0
        with:
          go-version: 1.18
        
      - run: |
          echo "Starting"
          go install tailscale.com/cmd/tailscale{,d}@main
          sudo $HOME/go/bin/tailscaled install-system-daemon
          tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname={github-ios-builder}
          tailscale status
          sleep 15

