# This is a basic workflow to help you get started with Actions

name: iOS Builder

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-12
    environment: development

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Setup Go environment
        uses: actions/setup-go@v3.3.0
        with:
          go-version: 1.19
        
      - run: |
          echo "Starting"
          go install tailscale.com/cmd/tailscale{,d}@main
          echo "Running tailscale daemon"
          sudo $HOME/go/bin/tailscaled install-system-daemon
          echo "Running tailscale"
          tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname={github-ios-builder}
          echo "DNS Setup"
          sudo networksetup -setdnsservers Ethernet 100.100.100.100
          echo "Sleeping"
          sleep 15
          echo "TS ping"
          tailscale ping anis-iphone -c 5
          echo "TS status"
          tailscale status
          echo "Pinging"
          dscacheutil -q host -a name anis-iphone
      - if: always()
        run: |
          echo "Bringing down tailscale"
          tailscale logout

